### ISSUE TITLE
build failure if compiled against 1.8.0

### ISSUE THREAD

**Issue by SolarAquarion** [grzegorzmazur/yagy#35]
45%] Building CXX object CMakeFiles/yagy.dir/yagy_autogen/mocs_compilation.cpp.o
In file included from /home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:22,
                 from /home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/anumber.h:9,
                 from /home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/numbers.h:5,
                 from /home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/lispatom.h:27,
                 from /home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/yacas.h:14,
                 from /home/solaraquarion/build/yagy/src/yagy-1.1.0/build/yagy_autogen/EWIEGA46WW/../../../yacasengine.h:14,
                 from /home/solaraquarion/build/yagy/src/yagy-1.1.0/build/yagy_autogen/EWIEGA46WW/../../../yacasserver.h:7,
                 from /home/solaraquarion/build/yagy/src/yagy-1.1.0/build/yagy_autogen/EWIEGA46WW/../../../cellproxy.h:8,
                 from /home/solaraquarion/build/yagy/src/yagy-1.1.0/build/yagy_autogen/EWIEGA46WW/moc_cellproxy.cpp:10,
                 from /home/solaraquarion/build/yagy/src/yagy-1.1.0/build/yagy_autogen/mocs_compilation.cpp:2:
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/nn.hpp:52:44: error: expected ‘)’ before ‘s’
   52 |                 ParseError(std::string_view s, std::size_t) :
      |                           ~                ^~
      |                                            )
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/nn.hpp:60:53: error: expected ‘)’ before ‘s’
   60 |                 DivisionByZeroError(std::string_view s) :
      |                                    ~                ^~
      |                                                     )
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/nn.hpp:72:41: error: expected ‘)’ before ‘,’ token
   72 |             explicit NN(std::string_view, unsigned b = 10);
      |                        ~                ^
      |                                         )
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/nn.hpp: In function ‘std::istream& yacas::mp::operator>>(std::istream&, yacas::mp::NN&)’:
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/nn.hpp:495:27: error: no matching function for call to ‘yacas::mp::NN::NN(std::string&, unsigned int&)’
  495 |             n = NN(s, base);
      |                           ^
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/nn.hpp:140:38: note: candidate: ‘template<class Iter> yacas::mp::NN::NN(Iter, Iter)’
  140 |             template <typename Iter> NN(Iter b, Iter e)
      |                                      ^~
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/nn.hpp:140:38: note:   template argument deduction/substitution failed:
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/nn.hpp:495:27: note:   deduced conflicting types for parameter ‘Iter’ (‘std::__cxx11::basic_string<char>’ and ‘unsigned int’)
  495 |             n = NN(s, base);
      |                           ^
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/nn.hpp:74:40: note: candidate: ‘template<class RndEngine> yacas::mp::NN::NN(unsigned int, RndEngine&)’
   74 |             template <class RndEngine> NN(unsigned no_bits, RndEngine& engine);
      |                                        ^~
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/nn.hpp:74:40: note:   template argument deduction/substitution failed:
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/nn.hpp:495:20: note:   cannot convert ‘s’ (type ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’}) to type ‘unsigned int’
  495 |             n = NN(s, base);
      |                    ^
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/nn.hpp:187:16: note: candidate: ‘yacas::mp::NN::NN(const std::vector<unsigned int, std::allocator<unsigned int> >&)’
  187 |         inline NN::NN(const std::vector<Limb>& limbs) : _limbs(limbs)
      |                ^~
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/nn.hpp:187:16: note:   candidate expects 1 argument, 2 provided
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/nn.hpp:181:16: note: candidate: ‘yacas::mp::NN::NN(yacas::mp::NN::Limb)’
  181 |         inline NN::NN(Limb n)
      |                ^~
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/nn.hpp:181:16: note:   candidate expects 1 argument, 2 provided
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/nn.hpp:67:13: note: candidate: ‘yacas::mp::NN::NN()’
   67 |             NN() = default;
      |             ^~
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/nn.hpp:67:13: note:   candidate expects 0 arguments, 2 provided
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/nn.hpp:34:15: note: candidate: ‘yacas::mp::NN::NN(const yacas::mp::NN&)’
   34 |         class NN {
      |               ^~
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/nn.hpp:34:15: note:   candidate expects 1 argument, 2 provided
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/nn.hpp:34:15: note: candidate: ‘yacas::mp::NN::NN(yacas::mp::NN&&)’
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/nn.hpp:34:15: note:   candidate expects 1 argument, 2 provided
In file included from /home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/anumber.h:9,
                 from /home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/numbers.h:5,
                 from /home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/lispatom.h:27,
                 from /home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/yacas.h:14,
                 from /home/solaraquarion/build/yagy/src/yagy-1.1.0/build/yagy_autogen/EWIEGA46WW/../../../yacasengine.h:14,
                 from /home/solaraquarion/build/yagy/src/yagy-1.1.0/build/yagy_autogen/EWIEGA46WW/../../../yacasserver.h:7,
                 from /home/solaraquarion/build/yagy/src/yagy-1.1.0/build/yagy_autogen/EWIEGA46WW/../../../cellproxy.h:8,
                 from /home/solaraquarion/build/yagy/src/yagy-1.1.0/build/yagy_autogen/EWIEGA46WW/moc_cellproxy.cpp:10,
                 from /home/solaraquarion/build/yagy/src/yagy-1.1.0/build/yagy_autogen/mocs_compilation.cpp:2:
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp: At global scope:
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:34:44: error: expected ‘)’ before ‘s’
   34 |                 ParseError(std::string_view s, std::size_t) :
      |                           ~                ^~
      |                                            )
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:41:53: error: expected ‘)’ before ‘s’
   41 |                 DivisionByZeroError(std::string_view s) :
      |                                    ~                ^~
      |                                                     )
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:51:41: error: expected ‘)’ before ‘s’
   51 |             explicit ZZ(std::string_view s, unsigned b = 10);
      |                        ~                ^~
      |                                         )
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp: In member function ‘yacas::mp::ZZ& yacas::mp::ZZ::operator/=(int)’:
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:281:54: error: no matching function for call to ‘yacas::mp::ZZ::DivisionByZeroError::DivisionByZeroError(std::string)’
  281 |                 throw DivisionByZeroError(to_string());
      |                                                      ^
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:40:20: note: candidate: ‘yacas::mp::ZZ::DivisionByZeroError::DivisionByZeroError(const yacas::mp::ZZ::DivisionByZeroError&)’
   40 |             struct DivisionByZeroError : public std::domain_error {
      |                    ^~~~~~~~~~~~~~~~~~~
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:40:20: note:   no known conversion for argument 1 from ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’} to ‘const yacas::mp::ZZ::DivisionByZeroError&’
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:40:20: note: candidate: ‘yacas::mp::ZZ::DivisionByZeroError::DivisionByZeroError(yacas::mp::ZZ::DivisionByZeroError&&)’
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:40:20: note:   no known conversion for argument 1 from ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’} to ‘yacas::mp::ZZ::DivisionByZeroError&&’
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp: In member function ‘yacas::mp::ZZ& yacas::mp::ZZ::operator%=(int)’:
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:298:54: error: no matching function for call to ‘yacas::mp::ZZ::DivisionByZeroError::DivisionByZeroError(std::string)’
  298 |                 throw DivisionByZeroError(to_string());
      |                                                      ^
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:40:20: note: candidate: ‘yacas::mp::ZZ::DivisionByZeroError::DivisionByZeroError(const yacas::mp::ZZ::DivisionByZeroError&)’
   40 |             struct DivisionByZeroError : public std::domain_error {
      |                    ^~~~~~~~~~~~~~~~~~~
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:40:20: note:   no known conversion for argument 1 from ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’} to ‘const yacas::mp::ZZ::DivisionByZeroError&’
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:40:20: note: candidate: ‘yacas::mp::ZZ::DivisionByZeroError::DivisionByZeroError(yacas::mp::ZZ::DivisionByZeroError&&)’
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:40:20: note:   no known conversion for argument 1 from ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’} to ‘yacas::mp::ZZ::DivisionByZeroError&&’
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp: In member function ‘yacas::mp::ZZ& yacas::mp::ZZ::operator/=(const yacas::mp::ZZ&)’:
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:380:54: error: no matching function for call to ‘yacas::mp::ZZ::DivisionByZeroError::DivisionByZeroError(std::string)’
  380 |                 throw DivisionByZeroError(to_string());
      |                                                      ^
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:40:20: note: candidate: ‘yacas::mp::ZZ::DivisionByZeroError::DivisionByZeroError(const yacas::mp::ZZ::DivisionByZeroError&)’
   40 |             struct DivisionByZeroError : public std::domain_error {
      |                    ^~~~~~~~~~~~~~~~~~~
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:40:20: note:   no known conversion for argument 1 from ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’} to ‘const yacas::mp::ZZ::DivisionByZeroError&’
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:40:20: note: candidate: ‘yacas::mp::ZZ::DivisionByZeroError::DivisionByZeroError(yacas::mp::ZZ::DivisionByZeroError&&)’
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:40:20: note:   no known conversion for argument 1 from ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’} to ‘yacas::mp::ZZ::DivisionByZeroError&&’
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp: In member function ‘yacas::mp::ZZ& yacas::mp::ZZ::operator%=(const yacas::mp::ZZ&)’:
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:396:54: error: no matching function for call to ‘yacas::mp::ZZ::DivisionByZeroError::DivisionByZeroError(std::string)’
  396 |                 throw DivisionByZeroError(to_string());
      |                                                      ^
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:40:20: note: candidate: ‘yacas::mp::ZZ::DivisionByZeroError::DivisionByZeroError(const yacas::mp::ZZ::DivisionByZeroError&)’
   40 |             struct DivisionByZeroError : public std::domain_error {
      |                    ^~~~~~~~~~~~~~~~~~~
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:40:20: note:   no known conversion for argument 1 from ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’} to ‘const yacas::mp::ZZ::DivisionByZeroError&’
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:40:20: note: candidate: ‘yacas::mp::ZZ::DivisionByZeroError::DivisionByZeroError(yacas::mp::ZZ::DivisionByZeroError&&)’
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:40:20: note:   no known conversion for argument 1 from ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’} to ‘yacas::mp::ZZ::DivisionByZeroError&&’
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp: In function ‘std::istream& yacas::mp::operator>>(std::istream&, yacas::mp::ZZ&)’:
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:540:27: error: no matching function for call to ‘yacas::mp::ZZ::ZZ(std::string&, unsigned int&)’
  540 |             z = ZZ(s, base);
      |                           ^
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:54:13: note: candidate: ‘template<class RndEngine> yacas::mp::ZZ::ZZ(unsigned int, RndEngine&)’
   54 |             ZZ(unsigned no_bits, RndEngine& engine);
      |             ^~
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:54:13: note:   template argument deduction/substitution failed:
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:540:20: note:   cannot convert ‘s’ (type ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’}) to type ‘unsigned int’
  540 |             z = ZZ(s, base);
      |                    ^
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:130:16: note: candidate: ‘yacas::mp::ZZ::ZZ(const yacas::mp::NN&)’
  130 |         inline ZZ::ZZ(const NN& n) : _nn(n), _neg(false) {}
      |                ^~
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:130:16: note:   candidate expects 1 argument, 2 provided
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:128:16: note: candidate: ‘yacas::mp::ZZ::ZZ(int)’
  128 |         inline ZZ::ZZ(int i) : _nn(std::abs(i)), _neg(i < 0) {}
      |                ^~
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:128:16: note:   candidate expects 1 argument, 2 provided
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:126:16: note: candidate: ‘yacas::mp::ZZ::ZZ()’
  126 |         inline ZZ::ZZ() : _neg(false) {}
      |                ^~
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:126:16: note:   candidate expects 0 arguments, 2 provided
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:26:15: note: candidate: ‘yacas::mp::ZZ::ZZ(const yacas::mp::ZZ&)’
   26 |         class ZZ {
      |               ^~
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:26:15: note:   candidate expects 1 argument, 2 provided
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:26:15: note: candidate: ‘yacas::mp::ZZ::ZZ(yacas::mp::ZZ&&)’
/home/solaraquarion/build/yagy/src/yagy-1.1.0/include/yacas/mp/zz.hpp:26:15: note:   candidate expects 1 argument, 2 provided
make[2]: *** [CMakeFiles/yagy.dir/build.make:953: CMakeFiles/yagy.dir/yagy_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/yagy.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by grzegorzmazur** [comment]
Hi,

Could you please provide some more details? First of all, what's the OS and which compiler do you use? Also it seems to me that you try to compile yagy, which in the meantime has been moved to the yacas repository and is now known as yacas-gui. Hence, when you compile yacas-1.8.0 you'll get the terminal application yacas and the GUI application, yacas-gui, which is just a newer version of yagy.

Please let me know if this resolves your issue.

Thanks,
Grzesiek

**Comment by SolarAquarion** [comment]
Gotcha, you should probably update the README

**Comment by grzegorzmazur** [comment]
Ups. Sorry :(

I've been convinced that I did it a long time ago. Actually, I've completely missed the fact that the bug report is in the yagy repository, which I considered frozen for years now. 

This time I've actually updated the README and I'll freeze the repository.

Sorry for the confusion,
Grzesiek
